apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinelops

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml

commonLabels:
  app: sentinelops
  managed-by: kustomize

images:
  - name: sentinelops-api
    newName: gcr.io/PROJECT_ID/sentinelops-api
    newTag: latest