failover:
  failover_rules:
  - action: route_to_us-east1
    condition: us-central1_unhealthy
    name: primary_failure
    priority: 1
  - action: route_to_us-west1
    condition: us-east1_unhealthy
    name: secondary_failure
    priority: 2
  - action: use_weighted_routing
    condition: all_regions_healthy
    name: all_healthy
    priority: 3
  health_check:
    failure_threshold: 3
    interval: 10
    success_threshold: 2
    timeout: 5
  monitoring:
    alert_channels:
    - email
    - slack
    metrics:
    - region_health_status
    - request_latency_by_region
    - error_rate_by_region
    - failover_events
  routing_policy:
    type: WEIGHTED
    weights:
      us-central1: 70
      us-east1: 20
      us-west1: 10
