# SentinelOps Threat Scenario Library
# 25 ready-made scenarios balanced across LOW/MEDIUM/CRITICAL severities

scenarios:
  # ═══════════════════════════════════════════════════════════════
  # LOW SEVERITY - Hygiene/Nuisance Issues (8 scenarios)
  # ═══════════════════════════════════════════════════════════════
  
  - id: LOW_001_BUCKET_PUBLIC
    severity: LOW
    category: "Data Exposure"
    mitre_tactic: "TA0009 - Collection"
    template: |
      {
        "event_type": "BUCKET_PUBLIC_READ",
        "resource": "gs://{{ bucket }}",
        "finding": "Public ACL detected on bucket",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single bucket exposure"
      }

  - id: LOW_002_WEAK_TLS
    severity: LOW
    category: "Configuration Drift"
    mitre_tactic: "TA0005 - Defense Evasion"
    template: |
      {
        "event_type": "TLS_WEAK_CIPHER",
        "target_service": "https://{{ fqdn }}",
        "protocol": "TLS1.0",
        "finding": "Deprecated cipher suite in use",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single service endpoint"
      }

  - id: LOW_003_UNUSED_KEY
    severity: LOW
    category: "Access Management"
    mitre_tactic: "TA0003 - Persistence"
    template: |
      {
        "event_type": "IAM_UNUSED_KEY",
        "user": "{{ user }}",
        "key_age_days": {{ key_age }},
        "finding": "Access key unused for >90 days",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single service account"
      }

  - id: LOW_004_UNPATCHED_OS
    severity: LOW
    category: "Patch Management"
    mitre_tactic: "TA0001 - Initial Access"
    template: |
      {
        "event_type": "OS_PATCH_MISSING",
        "target_vm": "{{ vm }}",
        "missing_patches": {{ patch_count }},
        "finding": "Non-critical OS patches missing",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single VM instance"
      }

  - id: LOW_005_OPEN_PORT
    severity: LOW
    category: "Network Security"
    mitre_tactic: "TA0007 - Discovery"
    template: |
      {
        "event_type": "UNNECESSARY_PORT_OPEN",
        "target_vm": "{{ vm }}",
        "port": {{ port }},
        "finding": "Non-essential port exposed to internet",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single VM network interface"
      }

  - id: LOW_006_LOG_RETENTION
    severity: LOW
    category: "Compliance"
    mitre_tactic: "TA0005 - Defense Evasion"
    template: |
      {
        "event_type": "LOG_RETENTION_SHORT",
        "resource": "{{ log_bucket }}",
        "retention_days": {{ retention }},
        "finding": "Log retention below compliance requirements",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Audit trail coverage"
      }

  - id: LOW_007_WEAK_PASSWORD
    severity: LOW
    category: "Access Management"
    mitre_tactic: "TA0006 - Credential Access"
    template: |
      {
        "event_type": "WEAK_PASSWORD_POLICY",
        "user": "{{ user }}",
        "policy_violations": {{ violations }},
        "finding": "Password policy not enforced",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single user account"
      }

  - id: LOW_008_STORAGE_QUOTA
    severity: LOW
    category: "Resource Management"
    mitre_tactic: "TA0040 - Impact"
    template: |
      {
        "event_type": "STORAGE_QUOTA_WARNING",
        "resource": "{{ storage_account }}",
        "usage_percent": {{ usage }},
        "finding": "Storage approaching quota limits",
        "severity": "LOW",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P3",
        "blast_radius": "Single storage account"
      }

  # ═══════════════════════════════════════════════════════════════
  # MEDIUM SEVERITY - Suspicious/Policy Violations (9 scenarios)
  # ═══════════════════════════════════════════════════════════════

  - id: MED_101_SUSPICIOUS_LOGIN
    severity: MEDIUM
    category: "Authentication Anomaly"
    mitre_tactic: "TA0001 - Initial Access"
    mitre_technique: "T1078 - Valid Accounts"
    template: |
      {
        "event_type": "SUSPICIOUS_LOGIN",
        "actor_ip": "{{ attacker_ip }}",
        "target_user": "{{ user }}",
        "country": "{{ country }}",
        "finding": "Login from unusual geolocation",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Single user account compromise risk"
      }

  - id: MED_102_PORT_SCAN
    severity: MEDIUM
    category: "Network Reconnaissance"
    mitre_tactic: "TA0007 - Discovery"
    mitre_technique: "T1046 - Network Service Scanning"
    template: |
      {
        "event_type": "PORT_SCAN",
        "actor_ip": "{{ attacker_ip }}",
        "target_subnet": "{{ subnet }}",
        "port_count": {{ ports }},
        "finding": "Horizontal port scan detected",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Network subnet reconnaissance"
      }

  - id: MED_103_PRIV_ESC
    severity: MEDIUM
    category: "Access Control"
    mitre_tactic: "TA0004 - Privilege Escalation"
    mitre_technique: "T1548 - Abuse Elevation Control Mechanism"
    template: |
      {
        "event_type": "PRIVILEGE_ESCALATION",
        "user": "{{ user }}",
        "new_role": "roles/editor",
        "finding": "Unapproved role elevation detected",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Elevated access to resources"
      }

  - id: MED_104_DNS_TUNNEL
    severity: MEDIUM
    category: "Command & Control"
    mitre_tactic: "TA0011 - Command and Control"
    mitre_technique: "T1071.004 - DNS"
    template: |
      {
        "event_type": "DNS_TUNNELING",
        "actor_ip": "{{ attacker_ip }}",
        "domain": "{{ domain }}",
        "qps": {{ qps }},
        "finding": "High-entropy DNS queries suggest tunneling",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Data exfiltration channel"
      }

  - id: MED_105_API_ABUSE
    severity: MEDIUM
    category: "Application Attack"
    mitre_tactic: "TA0009 - Collection"
    mitre_technique: "T1213 - Data from Information Repositories"
    template: |
      {
        "event_type": "API_RATE_ABUSE",
        "actor_ip": "{{ attacker_ip }}",
        "api_endpoint": "{{ api_endpoint }}",
        "requests_per_minute": {{ rpm }},
        "finding": "Abnormal API usage pattern detected",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "API service degradation"
      }

  - id: MED_106_CRYPTO_MINING
    severity: MEDIUM
    category: "Resource Hijacking"
    mitre_tactic: "TA0040 - Impact"
    mitre_technique: "T1496 - Resource Hijacking"
    template: |
      {
        "event_type": "CRYPTO_MINING_DETECTED",
        "target_vm": "{{ vm }}",
        "cpu_usage_percent": {{ cpu_usage }},
        "mining_pool": "{{ mining_pool }}",
        "finding": "Cryptocurrency mining activity detected",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Compute resource theft"
      }

  - id: MED_107_DATA_EXFIL_SMALL
    severity: MEDIUM
    category: "Data Exfiltration"
    mitre_tactic: "TA0010 - Exfiltration"
    mitre_technique: "T1041 - Exfiltration Over C2 Channel"
    template: |
      {
        "event_type": "SUSPICIOUS_DATA_TRANSFER",
        "actor_ip": "{{ attacker_ip }}",
        "data_volume_gb": {{ small_transfer }},
        "destination": "{{ external_ip }}",
        "finding": "Unusual outbound data transfer pattern",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Potential data exposure"
      }

  - id: MED_108_MALWARE_SIGNATURE
    severity: MEDIUM
    category: "Malware"
    mitre_tactic: "TA0002 - Execution"
    mitre_technique: "T1204 - User Execution"
    template: |
      {
        "event_type": "MALWARE_SIGNATURE_MATCH",
        "target_vm": "{{ vm }}",
        "signature_name": "{{ malware_sig }}",
        "file_hash": "{{ file_hash }}",
        "finding": "Known malware signature detected",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Single host infection"
      }

  - id: MED_109_INSIDER_THREAT
    severity: MEDIUM
    category: "Insider Risk"
    mitre_tactic: "TA0009 - Collection"
    mitre_technique: "T1005 - Data from Local System"
    template: |
      {
        "event_type": "UNUSUAL_ACCESS_PATTERN",
        "user": "{{ user }}",
        "access_count": {{ access_count }},
        "resources_accessed": {{ resource_count }},
        "finding": "Employee accessing unusual number of resources",
        "severity": "MEDIUM",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P2",
        "blast_radius": "Multiple resource exposure risk"
      }

  # ═══════════════════════════════════════════════════════════════
  # CRITICAL SEVERITY - Active Exploitation (8 scenarios)
  # ═══════════════════════════════════════════════════════════════

  - id: CRIT_201_SSH_BRUTE
    severity: CRITICAL
    category: "Brute Force Attack"
    mitre_tactic: "TA0006 - Credential Access"
    mitre_technique: "T1110.001 - Password Guessing"
    template: |
      {
        "event_type": "SSH_BRUTE_FORCE",
        "actor_ip": "{{ attacker_ip }}",
        "target_vm": "{{ vm }}",
        "match_count": {{ attacks }},
        "finding": "Active SSH brute force attack in progress",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Full system compromise risk"
      }

  - id: CRIT_202_RANSOMWARE_WRITE
    severity: CRITICAL
    category: "Ransomware"
    mitre_tactic: "TA0040 - Impact"
    mitre_technique: "T1486 - Data Encrypted for Impact"
    template: |
      {
        "event_type": "RANSOMWARE_FILE_WRITE",
        "target_vm": "{{ vm }}",
        "extension": ".crypted",
        "file_count": {{ files }},
        "finding": "Mass file encryption detected - ransomware active",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Data destruction/encryption"
      }

  - id: CRIT_203_CLOUDSQL_EXFIL
    severity: CRITICAL
    category: "Database Breach"
    mitre_tactic: "TA0010 - Exfiltration"
    mitre_technique: "T1020 - Automated Exfiltration"
    template: |
      {
        "event_type": "DB_BULK_DUMP",
        "db_instance": "{{ db }}",
        "dump_size_gb": {{ dump_size }},
        "actor_ip": "{{ attacker_ip }}",
        "finding": "Large database export - potential data theft",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Full database compromise"
      }

  - id: CRIT_204_WAF_BYPASS
    severity: CRITICAL
    category: "Application Attack"
    mitre_tactic: "TA0005 - Defense Evasion"
    mitre_technique: "T1055 - Process Injection"
    template: |
      {
        "event_type": "WAF_BYPASS",
        "target_service": "{{ fqdn }}",
        "payload_sample": "{{ payload }}",
        "finding": "WAF bypass successful - application compromise",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Application layer breach"
      }

  - id: CRIT_205_CONTAINER_ESCAPE
    severity: CRITICAL
    category: "Container Security"
    mitre_tactic: "TA0004 - Privilege Escalation"
    mitre_technique: "T1611 - Escape to Host"
    template: |
      {
        "event_type": "CONTAINER_ESCAPE",
        "container_id": "{{ container }}",
        "host_vm": "{{ vm }}",
        "escape_method": "{{ escape_technique }}",
        "finding": "Container breakout to host system detected",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Host system compromise"
      }

  - id: CRIT_206_SUPPLY_CHAIN
    severity: CRITICAL
    category: "Supply Chain Attack"
    mitre_tactic: "TA0001 - Initial Access"
    mitre_technique: "T1195 - Supply Chain Compromise"
    template: |
      {
        "event_type": "MALICIOUS_PACKAGE_DETECTED",
        "package_name": "{{ package }}",
        "version": "{{ version }}",
        "malware_family": "{{ malware_family }}",
        "finding": "Compromised dependency package installed",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Build pipeline compromise"
      }

  - id: CRIT_207_DDOS_ATTACK
    severity: CRITICAL
    category: "Denial of Service"
    mitre_tactic: "TA0040 - Impact"
    mitre_technique: "T1498 - Network Denial of Service"
    template: |
      {
        "event_type": "DDOS_ATTACK",
        "target_service": "{{ fqdn }}",
        "attack_volume_gbps": {{ attack_volume }},
        "attack_type": "{{ attack_type }}",
        "finding": "Large-scale DDoS attack in progress",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Service availability impact"
      }

  - id: CRIT_208_LATERAL_MOVEMENT
    severity: CRITICAL
    category: "Network Intrusion"
    mitre_tactic: "TA0008 - Lateral Movement"
    mitre_technique: "T1021 - Remote Services"
    template: |
      {
        "event_type": "LATERAL_MOVEMENT",
        "source_vm": "{{ source_vm }}",
        "target_vm": "{{ target_vm }}",
        "protocol": "{{ protocol }}",
        "finding": "Attacker moving between compromised systems",
        "severity": "CRITICAL",
        "timestamp": "{{ ts }}",
        "remediation_priority": "P1",
        "blast_radius": "Network-wide compromise risk"
      }

# Random value generation helpers
random_generators:
  bucket: "demo-{hex6}"
  fqdn: "app-{1-9}.example.com"
  user: ["alice@corp.com", "bob@corp.com", "svc-ci@corp.com", "admin@corp.com"]
  attacker_ip: "{1-254}.{1-254}.{1-254}.{1-254}"
  country: ["RU", "CN", "BR", "IR", "NG", "KP", "VN"]
  subnet: "10.{0-255}.{0-255}.0/24"
  ports: "{50-400}"
  vm: ["web-1", "web-2", "db-1", "api-1", "cache-1"]
  attacks: "{20-100}"
  dump_size: "{5.0-30.0}"
  db: ["orders-prod", "auth-prod", "analytics-db", "user-data-db"]
  files: "{200-5000}"
  domain: "{hex8}.bad.tld"
  qps: "{200-800}"
  payload: "{hex12}"
  key_age: "{90-365}"
  patch_count: "{3-15}"
  port: "{8080,3389,22,445,135}"
  log_bucket: "logs-{hex6}"
  retention: "{7-30}"
  violations: "{2-8}"
  storage_account: "storage-{hex4}"
  usage: "{85-95}"
  api_endpoint: "/api/v1/{endpoint}"
  rpm: "{1000-5000}"
  cpu_usage: "{80-100}"
  mining_pool: ["pool.minergate.com", "xmr-pool.com", "cryptonight.net"]
  small_transfer: "{1.5-8.0}"
  external_ip: "{external_ip_range}"
  malware_sig: ["Trojan.Win32.Agent", "PUP.Optional.Miner", "Backdoor.Linux.Mirai"]
  file_hash: "{sha256}"
  access_count: "{50-200}"
  resource_count: "{20-100}"
  container: "container-{hex8}"
  escape_technique: ["privileged_mount", "host_pid_namespace", "docker_socket"]
  package: ["eslint-scope", "event-stream", "ua-parser-js", "rc", "coa"]
  version: ["1.{minor}.{patch}"]
  malware_family: ["SolarWinds", "CodeCov", "Kaseya", "Log4Shell"]
  attack_volume: "{10-100}"
  attack_type: ["UDP_FLOOD", "SYN_FLOOD", "HTTP_FLOOD", "DNS_AMPLIFICATION"]
  source_vm: ["web-1", "web-2", "api-1"]
  target_vm: ["db-1", "admin-1", "backup-1"]
  protocol: ["RDP", "SSH", "WinRM", "SMB"]